when:
  event:
    - push
    - manual
  branch:
    - build-*
    - ci-*
    - dependencies
    - dependency-*
    - dependency
    - feature-*
    - fix-*
    - main
    - perf-*
    - refactor-*
    - release
    - style-*
    - test-*

depends_on:
  - check-secrets
  - infer-and-cache-version

variables:
  - &cache_volume '/home/container-runner/.local/share/docker/volumes-managed/woodpecker-ci-cache:/woodpecker/cache'
  - &source_cached_version source /woodpecker/cache/$CI_REPO/.version

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      partial: false
      tags: true

steps:
  - name: build
    image: registry.flyingfishflash.net/docker.io/node:22-alpine
    commands:
      - *source_cached_version
      - |
        cat <<EOT >> .build
        export BUILD_SCM_COMMIT_SHORT_SHA=$(echo $CI_COMMIT_SHA | cut -c1-8)
        export BUILD_NPM_CACHE=/woodpecker/cache/$CI_REPO/npm
        export BUILD_DIST=/woodpecker/cache/$CI_REPO/dist
        export PATH=./node_modules/.bin:$PATH
        EOT
      - source .build
      - env | awk -v s="BUILD_" 'index($0, s) == 1' | LC_ALL=C sort
      - mkdir -pv $BUILD_NPM_CACHE
      - mkdir -pv $BUILD_DIST    
      - |
        export JSON_BUILD_PROPERTIES=$(node -pe "
          JSON.stringify({
            artifact: new String('lorem-list'),
            ciPipelineId: process.env.CI_PIPELINE_NUMBER,
            ciPlatform: new String('woodpecker'),
            commit: process.env.BUILD_SCM_COMMIT_SHORT_SHA,
            group: Symbol(''),
            name: Symbol(''),
            time: Symbol(''),
            version: process.env.NYX_CURRENT_VERSION
          });
        ")
      - echo $JSON_BUILD_PROPERTIES > public/assets/buildProperties.json
      - cat public/assets/buildProperties.json
      - npm version $NYX_CURRENT_VERSION --no-git-tag-version
      - npm ci --cache $BUILD_NPM_CACHE --prefer-offline
      - ng version
      - ng build --configuration production --output-path=$BUILD_DIST/lorem-list-client-a
      - printf "\n$(ls -1a $BUILD_DIST/lorem-list-client-a | wc -l) files in $BUILD_DIST/lorem-list-client-a\n"
      - ls -la $BUILD_DIST/lorem-list-client-a      
    volumes: 
      - *cache_volume
