when:
  event:
    - manual
    - push
  branch:
    exclude: main

depends_on:
  - publish-image

variables:
  - &cache_volume '/home/container-runner/.local/share/docker/volumes-managed/woodpecker-ci-cache:/woodpecker/cache'
  - &export_cache_volume_deploy 'export CACHE_DEPLOY=/woodpecker/cache/$CI_REPO/deploy'
  - &source_cached_version 'source /woodpecker/cache/$CI_REPO/.version'

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      partial: false
      tags: true

steps:
  - name: create inventory file
    image: registry.flyingfishflash.net/docker.io/alpine
    environment:
      DEPLOY_TO_HOST:
        from_secret: deploy_to_host
    commands:
      - *export_cache_volume_deploy
      - mkdir -pv $CACHE_DEPLOY
      - echo "$DEPLOY_TO_HOST" > $CACHE_DEPLOY/inventory
      - cat $CACHE_DEPLOY/inventory
    volumes:
      - *cache_volume

  - name: create variables file
    image: registry.flyingfishflash.net/docker.io/alpine
    environment:
      DEPLOY_TO_HOST:
        from_secret: deploy_to_host
      REGISTRY_HOSTNAME:
        from_secret: registry_hostname
      OIDC_NAME:
        from_secret: oidc_name
      OIDC_ENDPOINT:
        from_secret: oidc_endpoint
      OIDC_CLIENT_ID:
        from_secret: oidc_client_id
      OIDC_SCOPE:
        from_secret: oidc_scope
      OIDC_ROLE_CLAIM:
        from_secret: oidc_role_claim
      OIDC_USERNAME_CLAIM:
        from_secret: oidc_username_claim
    commands:
      - *export_cache_volume_deploy
      - *source_cached_version
      - mkdir -pv $CACHE_DEPLOY
      - echo "---" > $CACHE_DEPLOY/variables.yaml
      - 'echo "tag: $NYX_CURRENT_VERSION" >> $CACHE_DEPLOY/variables.yaml'
      - 'echo "registry_url: $REGISTRY_HOSTNAME/lorem-list" >> $CACHE_DEPLOY/variables.yaml'
      - 'echo "deploy_to_host: $DEPLOY_TO_HOST" >> $CACHE_DEPLOY/variables.yaml'
      - 'echo "oidc_name: $OIDC_NAME" >> $CACHE_DEPLOY/variables.yaml'
      - 'echo "oidc_endpoint: $OIDC_ENDPOINT" >> $CACHE_DEPLOY/variables.yaml'
      - 'echo "oidc_client_id: $OIDC_CLIENT_ID" >> $CACHE_DEPLOY/variables.yaml'
      - 'echo "oidc_scope: $OIDC_SCOPE" >> $CACHE_DEPLOY/variables.yaml'
      - 'echo "oidc_role_claim: $OIDC_ROLE_CLAIM" >> $CACHE_DEPLOY/variables.yaml'
      - 'echo "oidc_username_claim: $OIDC_USERNAME_CLAIM" >> $CACHE_DEPLOY/variables.yaml'
      - ls -l $CACHE_DEPLOY
      - cat $CACHE_DEPLOY/inventory
      - cat $CACHE_DEPLOY/variables.yaml
    volumes:
      - *cache_volume
